#ifndef _H_RESOURCE_TYPES
#define _H_RESOURCE_TYPES

enum RESOURCE_TYPE
{
	RT_RESOURCE = 0,
	RT_SHADER_RESOURCE,
	RT_TEXTURE_RESOURCE,
	RT_BSP_RESOURCE,
	RT_SOUND_RESOURCE,
	RT_MUSIC_RESOURCE,
	RT_MD3_RESOURCE,
	RT_CACHE_RESOURCE,
	RT_INDEXBUFFER_RESOURCE,
	RT_VERTEXBUFFER_RESOURCE,
	RT_PLAYER_RESOURCE,
	RT_WEAPON_RESOURCE,
	RT_FOOTSTEP_RESOURCE,

	//todo, include all other resource types in here
};

#endif